resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: Artifactory
      fileLocation: deploy-generic-local # name of the artifactory from which one need to deploy the file
     
pipelines:
  - name: pipelines_file # Name of pipeline
    steps:
      - name: REFILE_1
        type: bash
        configuration:
          nodePool: default-dynamic-nodepool # Name of node pool
          integrations:
            - name: Artifactory
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - echo "executing step..."
            - jfrog rt dl deploy-generic-local/vraj.sh
            - ls
            - bash vraj.sh
            - ssh -tt $int_pemfile_key ec2-user@18.212.183.89
        
