resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: Artifactory
      fileLocation: generic-generic-local # name of the artifactory from which one need to deploy the file
     
pipelines:
  - name: pipelines_file # Name of pipeline
    steps:
      - name: REFILE_1
        type: bash
        configuration:
          nodePool: default-dynamic-nodepool # Name of node pool
          integrations:
            - name: Artifactory
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - echo "executing step..."
            - jfrog rt dl generic-generic-local --sort-by=created --sort-order=desc --limit=1
        
