resources:
  - name: RemoteFile_1
    type: RemoteFile
    configuration:
      source: Artifactory
      fileLocation: deploy-generic-local # name of the artifactory from which one need to deploy the file
     
pipelines:
  - name: pipelines_file # Name of pipeline
    steps:
      - name: REFILE_1
        type: bash
        configuration:
          nodePool: default-dynamic-nodepool # Name of node pool
          integrations:
            - name: Artifactory
            - name: aws
          outputResources:
            - name: RemoteFile_1
        execution:
          onExecute:
            - echo "executing step..."
            - jfrog rt dl deploy-generic-local/vraj.sh
            - jfrog rt dl deploy-generic-local/frog.sh
            - ls -a
            - bash vraj.sh
            - sudo apt install sshpass
            - echo "executing"
            - sshpass -p "$int_aws_pass" scp ./vraj.sh root@52.90.172.23:/vraj.sh
            - ls -a
            
            
        
